#!/bin/sh

# Close current Google Chrome window if any
wmctrl -c chrome

# Retrieve current kiosk parameters
width=$(get_parameter width)
height=$(get_parameter height)
version=$(get_parameter version)
server_ip=$(get_parameter server_ip)

# Set screen resolution
xrandr -s ${width}x${height}

# Open Google Chrome in kiosk mode
google-chrome --kiosk http://${server_ip}/kPanel/versions/${version}.html

