#!/bin/sh

# Close current Google Chrome window if any
wmctrl -c chrome

# Retrieve current kiosk parameters
video_group=$(./get_parameter video_group)
video_mode=$(./get_parameter video_mode)
version=$(./get_parameter version)
server_ip=$(./get_parameter server_ip)

# Set screen resolution
tvservice -e "${video_group} ${video_mode}"

# Open Google Chrome in kiosk mode
chrome --kiosk http://${server_ip}/kPanel/versions/${version}.html &
